# Generated by Django 4.2.6 on 2023-10-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('cars_image', models.ImageField(upload_to='cars_image')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
